import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { chromium } from 'playwright';

mkdirSync('.vercel', { recursive: true });
const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'chrome', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(process.env.TEST_URL || 'http://localhost:3001');
  await page.selectOption('#deckSelect', 'accenture-2ji');
  await page.selectOption('#recallMode', 'words');
  const light = await page.locator('.word-blank').count();
  assert.ok(light > 0);
  assert.equal(await page.locator('#btnKnown').isDisabled(), true);
  await page.selectOption('#wordLevel', 'all');
  assert.ok(await page.locator('.word-blank').count() >= light);
  await page.click('#wordHint');
  assert.equal(await page.locator('.word-blank.is-revealed').count(), 1);
  await page.click('#wordReveal');
  assert.equal(await page.locator('#btnKnown').isDisabled(), false);
  const original = await page.evaluate(() => window.QA_DATA.decks.find(d=>d.id==='accenture-2ji').categories[0].questions[0].answer);
  assert.equal(await page.textContent('#wordAnswer'), original);
  await page.click('#wordRetry');
  assert.equal(await page.locator('#btnKnown').isDisabled(), true);
  await page.locator('.word-blank').first().focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('.word-blank.is-revealed').count(), 1);
  await page.locator('.word-editor summary').click();
  await page.locator('.word-choice').first().click();
  assert.equal(await page.inputValue('#wordLevel'), 'custom');
  const selected = await page.locator('.word-choice[aria-pressed=true]').count();
  await page.reload();
  await page.selectOption('#recallMode', 'words');
  await page.selectOption('#wordLevel', 'custom');
  assert.equal(await page.locator('.word-blank').count(), selected);
  await page.click('#wordReveal');
  await page.click('#btnKnown');
  assert.equal(await page.locator('#btnKnown').isDisabled(), true);
  await page.click('#btnUndoReview');
  assert.equal(await page.textContent('#wordAnswer'), original);
  await page.click('#btnKnown');
  // Long answer and supplement, mobile and keyboard controls.
  await page.selectOption('#wordLevel', 'all');
  await page.click('#wordReveal');
  assert.equal(await page.locator('#wordPoint').isVisible(), true);
  await page.click('#wordRetry');
  await page.screenshot({ path: '.vercel/words-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth), true);
  await page.locator('.word-editor summary').click();
  while (await page.locator('.word-choice[aria-pressed=true]').count()) await page.locator('.word-choice[aria-pressed=true]').first().click();
  assert.equal(await page.locator('#btnKnown').isDisabled(), true);
  assert.match(await page.textContent('#wordStatus'), /1つ以上/);
  await page.selectOption('#deckSelect', 'general');
  await page.selectOption('#wordLevel','light');
  assert.ok(await page.locator('.word-blank').count()>0);
  await page.selectOption('#recallMode','card');
  assert.equal(await page.locator('#flashCard').count(),1);
  await page.click('#flashCard');
  assert.equal(await page.locator('#btnKnown').isDisabled(),false);
  assert.deepEqual(errors,[]);
  console.log('PASS: masks, levels, hints, keyboard reveal, exact answer, custom persistence, empty selection, review integration, undo, mobile layout, original cards');
} finally { await browser.close(); }
